# Generated by Django 5.2.3 on 2025-07-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_company'),
        ('projects', '0003_project_company'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linked_projects',
            field=models.ManyToManyField(blank=True, to='projects.project'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_properties',
            field=models.ManyToManyField(blank=True, to='properties.property'),
        ),
    ]
