# Generated by Django 5.2.4 on 2025-07-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='linked_projects',
        ),
    ]
