# Generated by Django 5.2.4 on 2025-07-27 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_linked_projects'),
        ('projects', '0003_project_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='key_stakeholder',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='project',
            name='property_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROPERTY_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='project',
            name='stakeholders',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='project',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='projects_involved', to='contacts.contact'),
        ),
    ]
