# Generated by Django 5.2.4 on 2025-07-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_linked_projects'),
        ('projects', '0004_remove_project_key_stakeholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_stakeholder_projects', to='contacts.contact'),
        ),
    ]
