# Generated by Django 5.2.4 on 2025-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_created_at_project_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='proposed', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('construction', 'Construction'), ('interior', 'Interior')], default='internal', max_length=50),
        ),
    ]
