# Generated by Django 5.2.3 on 2025-08-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
