# Generated by Django 5.2.4 on 2025-07-09 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('cost_centre_id', models.AutoField(help_text='Unique identifier for the cost centre', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name of the cost centre', max_length=255)),
                ('transaction_direction', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Both', 'Both')], default='Both', help_text='Allowed transaction direction: Credit, Debit, or Both', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or description for the cost centre')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag; inactive cost centres are not shown in active listings')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this cost centre was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this cost centre was last updated')),
                ('company', models.ForeignKey(help_text='Company this cost centre belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cost_centres', to='companies.company')),
            ],
            options={
                'verbose_name': 'Cost Centre',
                'verbose_name_plural': 'Cost Centres',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
