# Generated by Django 5.2.4 on 2025-07-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_contract_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='asset',
        ),
    ]
