# Generated by Django 5.2.4 on 2025-07-09 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('companies', '0001_initial'),
        ('cost_centres', '0001_initial'),
        ('entities', '0001_initial'),
        ('transaction_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('gst_applicable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='receipt_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost_centres.costcentre')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity')),
                ('transaction_type', models.ForeignKey(limit_choices_to={'direction': 'Credit'}, on_delete=django.db.models.deletion.CASCADE, to='transaction_types.transactiontype')),
            ],
        ),
    ]
