# Generated by Django 5.2.3 on 2025-08-13 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('bank_uploads', '0001_initial'),
        ('contracts', '0003_remove_contract_asset'),
        ('cost_centres', '0001_initial'),
        ('entities', '0001_initial'),
        ('transaction_types', '0002_transactiontype_is_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classification_id', models.UUIDField(db_column='classification_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('value_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active_classification', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('bank_transaction', models.ForeignKey(db_column='bank_transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='bank_uploads.banktransaction')),
                ('contract', models.ForeignKey(blank=True, db_column='contract_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract')),
                ('cost_centre', models.ForeignKey(db_column='cost_centre_id', on_delete=django.db.models.deletion.PROTECT, to='cost_centres.costcentre')),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.PROTECT, to='entities.entity')),
                ('transaction_type', models.ForeignKey(db_column='transaction_type_id', on_delete=django.db.models.deletion.PROTECT, to='transaction_types.transactiontype')),
            ],
            options={
                'db_table': 'tx_classify_transactionclassification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bank_transaction'], name='tx_classify_bank_tr_dcce8c_idx'), models.Index(fields=['is_active_classification'], name='tx_classify_is_acti_4ec9f4_idx')],
            },
        ),
    ]
