# Generated by Django 5.2.3 on 2025-08-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='purchase_price',
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, default='Kerala', max_length=100, null=True),
        ),
    ]
