# Generated by Django 5.2.4 on 2025-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('sold', 'Sold'), ('not_for_rent', 'Not for Rent'), ('owner_occupied', 'Owner occupied'), ('tenant_occupied', 'Tenant occupied'), ('under_maintenance', 'Under maintenance')], default='vacant', max_length=20),
        ),
    ]
