# Generated by Django 5.2.4 on 2025-08-15 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_linked_projects'),
        ('properties', '0003_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_properties', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_properties', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('plot', 'Plot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('under maintenance', 'Under maintenance'), ('owner occupied', 'Owner occupied'), ('tenant occupied', 'Tenant occupied'), ('sold', 'Sold'), ('not for rent', 'Not for Rent')], default='vacant', max_length=20),
        ),
    ]
