# Generated by Django 5.2.4 on 2025-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_landlord_property_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='landlord',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('plot', 'Plot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('sold', 'Sold'), ('not_for_rent', 'Not for Rent'), ('owner_occupied', 'Owner occupied'), ('tenant_occupied', 'Tenant occupied'), ('under_maintenance', 'Under maintenance')], default='vacant', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='tenant',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
