# Generated by Django 5.2.4 on 2025-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_landlord_alter_property_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('sold', 'Sold'), ('not_for_rent', 'Not for Rent')], default='vacant', max_length=20),
        ),
    ]
