# Generated by Django 5.2.4 on 2025-08-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_landlord_remove_property_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('sold', 'Sold'), ('not_for_rent', 'Not for Rent'), ('under_maintenance', 'Under Maintenance'), ('owner_occupied', 'Owner Occupied'), ('tenant_occupied', 'Tenant Occupied')], default='vacant', max_length=20),
        ),
    ]
