# Generated by Django 5.2.4 on 2025-08-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('sold', 'Sold'), ('not_for_rent', 'Not for Rent')], default='vacant', max_length=20),
        ),
    ]
