# Generated by Django 5.2.4 on 2025-07-11 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('assets', '0001_initial'),
        ('contracts', '0001_initial'),
        ('cost_centres', '0001_initial'),
        ('entities', '0001_initial'),
        ('transaction_types', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedTransaction',
            fields=[
                ('classification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active_classification', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract')),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_centres.costcentre')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='transactions.transaction')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction_types.transactiontype')),
            ],
        ),
    ]
