# Generated by Django 5.2.3 on 2025-08-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('banks', '0001_initial'),
        ('companies', '0002_company_is_active'),
        ('contracts', '0003_remove_contract_asset'),
        ('cost_centres', '0001_initial'),
        ('entities', '0001_initial'),
        ('transaction_types', '0002_transactiontype_is_credit'),
        ('transactions', '0002_classifiedtransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifiedtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='classifiedtransaction',
            name='bank_account',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.bankaccount'),
        ),
        migrations.AddField(
            model_name='classifiedtransaction',
            name='company',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='classifiedtransaction',
            name='parent_transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classifiedtransaction',
            name='parent_transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='classifiedtransaction',
            index=models.Index(fields=['company'], name='transaction_company_4a6bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='classifiedtransaction',
            index=models.Index(fields=['bank_account'], name='transaction_bank_ac_0db800_idx'),
        ),
        migrations.AddIndex(
            model_name='classifiedtransaction',
            index=models.Index(fields=['is_active_classification'], name='transaction_is_acti_622d3b_idx'),
        ),
    ]
