# Generated by Django 5.2.3 on 2025-08-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_classifiedtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedtransaction',
            name='transaction_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
