# Generated by Django 5.2.3 on 2025-08-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_classifiedtransaction_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedtransaction',
            name='transaction_date',
        ),
    ]
