# Generated by Django 5.2.3 on 2025-08-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_classifiedtransaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedtransaction',
            name='direction',
            field=models.CharField(choices=[('CREDIT', 'Credit (Income)'), ('DEBIT', 'Debit (Expense)')], editable=False, max_length=6, null=True),
        ),
    ]
