# Generated by Django 5.2.4 on 2025-07-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLedgerCombined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('BANK', 'BANK'), ('CASH', 'CASH')], max_length=10)),
            ],
            options={
                'db_table': 'v_transaction_ledger_combined',
                'managed': False,
            },
        ),
    ]
