# Generated by Django 5.2.4 on 2025-07-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionledgercombined',
            options={'managed': False, 'verbose_name_plural': 'Transaction Ledger Combined'},
        ),
    ]
