# Generated by Django 5.2.4 on 2025-07-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_transactionledgercombined_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionledgercombined',
            options={'managed': False},
        ),
    ]
