# Generated by Django 5.2.4 on 2025-07-17 17:09

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('Contractor', 'Contractor'), ('Supplier', 'Supplier'), ('Consultant', 'Consultant')], max_length=50)),
                ('pan_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid PAN format', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid GST format', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('contact_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone must be 10 digits', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid IFSC Code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('company_id', models.UUIDField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
            ],
        ),
    ]
