# Generated by Django 5.2.3 on 2025-07-19 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='GST must be a valid 15-character alphanumeric code', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ifsc_code',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='IFSC must be 11 characters (e.g. HDFC0XXXXXX)', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='PAN must be a valid 10-character alphanumeric string (e.g. ABCDE1234F)', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone must be a 10-digit number', regex='^\\d{10}$')]),
        ),
    ]
