# Generated by Django 5.2.4 on 2025-07-28 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_is_active'),
        ('vendors', '0002_alter_vendor_gst_number_alter_vendor_ifsc_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='created_by',
        ),
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
