# Generated by Django 5.2.4 on 2025-07-09 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the entity', max_length=255)),
                ('entity_type', models.CharField(choices=[('Property', 'Property'), ('Project', 'Project'), ('Internal', 'Internal')], help_text='Entity type: Property, Project, or Internal', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Entity status: Active or Inactive', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks about the entity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the entity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated')),
                ('company', models.ForeignKey(blank=True, help_text='Company this entity belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='companies.company')),
                ('linked_project', models.ForeignKey(blank=True, help_text='Linked project if entity_type=Project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('linked_property', models.ForeignKey(blank=True, help_text='Linked property if entity_type=Property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
