# Generated by Django 5.2.4 on 2025-08-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_linked_projects'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='linked_contact',
            field=models.ForeignKey(blank=True, help_text='Linked contact if entity_type=Contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities_as_contact', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('Property', 'Property'), ('Project', 'Project'), ('Internal', 'Internal'), ('Contact', 'Contact')], help_text='Entity type: Property, Project, Internal, or Contact', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated at'),
        ),
    ]
