# Generated by Django 5.2.4 on 2025-08-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_linked_projects'),
        ('entities', '0002_entity_linked_contact_alter_entity_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the entity was created'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('Property', 'Property'), ('Project', 'Project'), ('Contact', 'Contact'), ('Internal', 'Internal')], help_text='Entity type: Property, Project, Contact, or Internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='linked_contact',
            field=models.ForeignKey(blank=True, help_text='Linked contact if entity_type=Contact', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated'),
        ),
    ]
