# Generated by Django 5.2.4 on 2025-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashledgerregister',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='cash_ledger_docs/'),
        ),
    ]
