# Generated by Django 5.2.4 on 2025-07-09 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('cost_centres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transaction_type_id', models.AutoField(help_text='Unique identifier for the transaction type', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name of the transaction type', max_length=255)),
                ('direction', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', help_text='Transaction direction: Credit or Debit', max_length=10)),
                ('gst_applicable', models.BooleanField(default=False, help_text='Whether GST is applicable for this transaction type')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Status of the transaction type: Active or Inactive', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks about the transaction type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the transaction type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the transaction type was last updated')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_types', to='companies.company')),
                ('cost_centre', models.ForeignKey(blank=True, help_text='Cost centre linked to this transaction type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_types', to='cost_centres.costcentre')),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
