# Generated by Django 5.2.4 on 2025-07-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
